from graphics import *
win = GraphWin('Temperature Converter', 400, 300)
win.setCoords(0.0, 0.0, 3.0, 4.0)
Text(Point(1, 3), " Celsius Temperature:").draw(win)
Text(Point(1, 1), " Fahrenheit Temperature: ").draw(win)
Input = Entry(Point(2, 3), 5)
Input.setText('0.0')
Input.draw(win)
Output = Text(Point(2, 1), "")
Output.draw(win)
button = Text(Point(1.5, 2.0), "Convert It")
button.draw(win)
Rectangle(Point(1, 1.5), Point(2, 2.5)).draw(win)
win.getMouse()
celsius = eval(Input.getText())
fahrenheit = 9.0/5.0 * celsius + 32
Output.setText(fahrenheit)
button.setText('Quit')
win.getMouse()
win.close()
